### ISSUE TITLE
git-fleximod no longer works

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#21]
With the latest push to ESCOMP/CAM #989, I get the following:

izumi$ git checkout zz_rme/cam6_3_150
Updating files: 100% (2207/2207), done.
branch 'zz_rme/cam6_3_150' set up to track 'origin/zz_rme/cam6_3_150'.
Switched to a new branch 'zz_rme/cam6_3_150'
izumi$ bin/git-fleximod update
Traceback (most recent call last):
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/.lib/git-fleximod/git_fleximod/gitinterface.py", line 17, in __init__
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/bin/git-fleximod", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 513, in main
    submodules_update(gitmodules, root_dir, fxrequired, force)
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 307, in submodules_update
    _, localmods, needsupdate = submodules_status(gitmodules, root_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 252, in submodules_status
    rootgit = GitInterface(root_dir, logger)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/cluster/cacraig/cam5_remove_manage_externals/.lib/git-fleximod/git_fleximod/gitinterface.py", line 28, in __init__
    if not (repo_path / ".git").exists():
            ~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by jedwards4b** [comment]
@cacraigucar Thank you for opening an issue here, I'm not sure why I missed it until now.
I just tried and I had not at all the same experience as you did on izumi - any idea why?  I was able to clone and checkout this cam branch without any problems.   
/home/jedwards/cam6_3_150.rme 
python --version
Python 3.7.0

```
git clone https://github.com/jedwards4b/CAM -b zz_rme/cam6_3_150 cam6_3_150.rme
Cloning into 'cam6_3_150.rme'...
remote: Enumerating objects: 36908, done.
remote: Counting objects: 100% (2448/2448), done.
remote: Compressing objects: 100% (1120/1120), done.
remote: Total 36908 (delta 1473), reused 2143 (delta 1256), pack-reused 34460
Receiving objects: 100% (36908/36908), 40.34 MiB | 31.70 MiB/s, done.
Resolving deltas: 100% (26550/26550), done.
Updating files: 100% (2207/2207), done.
[jedwards@izumi ~]$ cd cam6_3_150.rme/
[jedwards@izumi cam6_3_150.rme]$ ./bin/git-fleximod update
e            chem_proc not checked out, aligned at tag chem_proc5_0_05
e                carma not checked out, aligned at tag carma4_01
e                cosp2 not checked out, aligned at tag v2.1.4cesm
e                clubb not checked out, aligned at tag clubb_4ncar_20221129_59cb19f_20230330_branchtag
e                pumas not checked out, aligned at tag pumas_cam-release_v1.35
e         pumas-frozen not checked out, aligned at tag pumas_cam-release_v1.17_rename
e             ali_arms not checked out, aligned at tag ALI_ARMS_v1.0.1
e           atmos_phys not checked out, aligned at tag atmos_phys0_02_000
e   atmos_cubed_sphere not checked out, aligned at tag fv3_cesm.04
e                 mpas not checked out, aligned at hash b8c33daa
e             geoschem not checked out, aligned at tag 14.1.2
e                hemco not checked out, out of sync at tag None, expected tag is rme/hemco-cesm1_2_1_hemco3_6_3_cesm
e           rte-rrtmgp not checked out, aligned at tag v1.7
e          rrtmgp-data not checked out, aligned at tag v1.8
Successfully checked out           ccs_config
          ccs_config up to date.
Successfully checked out                cice5
               cice5 up to date.
Recursively checking out submodules of cice6

e                 cice not checked out, aligned at tag cice6_5_0_20240222
Recursively checking out submodules of cice

e              icepack has no fxtag defined in .gitmodules
Successfully checked out              icepack
Successfully checked out                 cice
Successfully checked out                cice6
               cice6 updated to rme/cesm_cice6_5_0_7
Successfully checked out                cmeps
               cmeps up to date.
Recursively checking out submodules of cdeps

e                  fox not checked out, aligned at tag 4.1.2.1
e               genf90 not checked out, aligned at hash 4816965
Successfully checked out                  fox
Successfully checked out               genf90
Successfully checked out                cdeps
               cdeps updated to rme/cdeps1.0.28
Successfully checked out                 cpl7
                cpl7 up to date.
Successfully checked out                share
               share up to date.
Successfully checked out                  mct
                 mct up to date.
Successfully checked out           parallelio
          parallelio up to date.
Recursively checking out submodules of cime
e    CIME/non_py/cprnc not checked out, aligned at tag v1.0.6
Successfully checked out    CIME/non_py/cprnc

Successfully checked out                 cime
                cime up to date.
Successfully checked out                 cism
                cism up to date.
Recursively checking out submodules of clm

e                fates not checked out, aligned at tag sci.1.71.0_api.33.0.0
Successfully checked out                fates
Successfully checked out                  clm
                 clm up to date.
Successfully checked out                  fms
                 fms up to date.
Successfully checked out               mosart
              mosart up to date.
Successfully checked out                  rtm
                 rtm up to date.
Successfully checked out            chem_proc
           chem_proc up to date.
Successfully checked out                carma
               carma up to date.
Successfully checked out                cosp2 at v2.1.4cesm
               cosp2 up to date.
Successfully checked out                clubb at clubb_4ncar_20221129_59cb19f_20230330_branchtag
               clubb up to date.
Successfully checked out                pumas
               pumas up to date.
Successfully checked out         pumas-frozen
        pumas-frozen up to date.
Successfully checked out             ali_arms
            ali_arms up to date.
Successfully checked out           atmos_phys
          atmos_phys up to date.
Successfully checked out   atmos_cubed_sphere
  atmos_cubed_sphere up to date.
Successfully checked out                 mpas at b8c33daa
                mpas updated to b8c33daa
Successfully checked out             geoschem
            geoschem up to date.
Recursively checking out submodules of hemco

e                HEMCO not checked out, aligned at tag 3.6.3-cesm
Recursively checking out submodules of HEMCO

e docs/source/geos-chem-shared-docs has no fxtag defined in .gitmodules
Successfully checked out docs/source/geos-chem-shared-docs
Successfully checked out                HEMCO
Successfully checked out                hemco
               hemco updated to rme/hemco-cesm1_2_1_hemco3_6_3_cesm
Successfully checked out           rte-rrtmgp
          rte-rrtmgp up to date.
Successfully checked out          rrtmgp-data
         rrtmgp-data up to date.
```

**Comment by jedwards4b** [comment]
I was able to reproduce  your error after loading 
 lang/python/3.11.5.  looking into it now.

**Comment by jedwards4b** [comment]
@cacraigucar I found the issue and pushed a fix to zz_rme/cam6_3_150
