### ISSUE TITLE
"MemoryError" on windows machine

### ISSUE THREAD

**Issue by olyson** [ESMCI/git-fleximod#41]
For the purposes of building CTSM documentation on my windows machine (running Windows 11) I did the following using PowerShell:

cd C:\Users\oleson\ctsm-repos
git clone https://github.com/ESCOMP/CTSM.git ./ctsm_masterdoc
cd ctsm_masterdoc
python .\bin\git-fleximod update -o

but got the following "MemoryError":

```
python : Traceback (most recent call last):
At line:1 char:1
+ python .\bin\git-fleximod update -o
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteExcep 
   tion
    + FullyQualifiedErrorId : NativeCommandError
 
  File ".\bin\git-fleximod", line 8, in <module>
    sys.exit(main())
  File "C:\Users\oleson\ctsm-repos\ctsm_masterdoc\.lib\git-fleximod\git_fleximod\git_fleximod.py", line 
556, in main
    ) = commandline_arguments()
  File "C:\Users\oleson\ctsm-repos\ctsm_masterdoc\.lib\git-fleximod\git_fleximod\git_fleximod.py", line 
27, in commandline_arguments
    parser = cli.get_parser()
  File "C:\Users\oleson\ctsm-repos\ctsm_masterdoc\.lib\git-fleximod\git_fleximod\cli.py", line 56, in 
get_parser
    default=find_root_dir(),
  File "C:\Users\oleson\ctsm-repos\ctsm_masterdoc\.lib\git-fleximod\git_fleximod\cli.py", line 15, in 
find_root_dir
    dirlist.append(dl)
MemoryError
```

I have python 3.7

**Comment by jedwards4b** [comment]
Hi Keith - this is the first mention of windows I have seen.   For this purpose I think that you don't need to use git-fleximod at all.  Instead try `git submodule update --init`

**Comment by olyson** [comment]
That works, thanks.
