### ISSUE TITLE
Error in a CTSM branch that includes cam6_4_016 with v0.8.2 and v0.8.4

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/git-fleximod#59]
In branch_tags/dustemisdev.n08_ctsm5.2.018 which includes CAM and CICE there is a gitfleximod issue when trying to update cam. The only thing needed from this branch is the .gitmodules file

https://github.com/ESCOMP/CTSM/blob/branch_tags/dustemisdev.n08_ctsm5.2.018/.gitmodules

Doing

``` shell
bin/git-fleximod update cam
```

results in an error as below.

I've tried this both with v0.7.8, v0.8.2 and the latest v0.8.4. The error I see with the latest is:

```
bin/git-fleximod update cam
                 cam up to date.
Recursively checking out submodules of cam
Recursively checking out submodules of fv3
Recursively checking out submodules of hemco
Recursively checking out submodules of HEMCO
Sparse checkout mpas fxsparse ../.mpas_sparse_checkout
Traceback (most recent call last):
  File "bin/git-fleximod", line 8, in <module>
    sys.exit(main())
  File "/glade/work/erik/ctsm_worktrees/external_updates/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 350, in main
    submodules_update(gitmodules, root_dir, fxrequired, force)
  File "/glade/work/erik/ctsm_worktrees/external_updates/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 254, in submodules_update
    submodules_update(gitsubmodules, repodir, newrequiredlist, force=force)
  File "/glade/work/erik/ctsm_worktrees/external_updates/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 244, in submodules_update
    submod.update()
  File "/glade/work/erik/ctsm_worktrees/external_updates/.lib/git-fleximod/git_fleximod/submodule.py", line 334, in update
    self.sparse_checkout()
  File "/glade/work/erik/ctsm_worktrees/external_updates/.lib/git-fleximod/git_fleximod/submodule.py", line 222, in sparse_checkout
    assert os.path.isdir(os.path.join(gitroot, ".git"))
AssertionError
```

**Comment by ekluzek** [comment]
@cacraigucar you must have gitfleximod working for cam in cam6_4_16, what might be different about what I'm doing than what you are doing for CAM?

**Comment by jedwards4b** [comment]
Yes cam6_4_016 is working for other projects such as cesm3_0_beta02.   Have you exceeded your disk quota?

**Comment by cacraigucar** [comment]
@ekluzek - Yes, numerous people have checked out cam6_4_016 (and subsequent versions) without any issue.  If you still have a problem, please let me know.

**Comment by ekluzek** [comment]
@billsacks with try checking this out in a worktree of CTSM and see if he sees the same thing.

I did check quota, and it looks like that's NOT the problem. But, it was a great suggestion. 

I do have it working doing a new clone under $SCRATCH for example. And similarly cam6_4_016 works for me. I'll also try CESM. It might just be an issue with git worktree's?  But I'm not completely sure.

**Comment by jedwards4b** [comment]
I would be happy to look into the git worktree issue but I will need a crash course on how to use that git feature.

**Comment by cacraigucar** [comment]
@jedwards4b - This looks like it might be a good tutorial (I've spent all of 2 minutes looking at it, but it was recommended to me by someone else).   https://www.gitkraken.com/learn/git/git-worktree

**Comment by billsacks** [comment]
Yes, I can reproduce this error, and it seems related to the use of git worktrees. The issue seems to be that, in a git worktree, `.git` is not a directory: instead, it is a plain text file pointing back to the .git directory in the original git clone.

Steps to reproduce:

```
git clone git@github.com:ESCOMP/CTSM.git CTSM2
cd CTSM2
git worktree add --detach ../CTSM3
./bin/git-fleximod update  # I'm not sure if this step is necessary to reproduce the issue
cd ../CTSM3
git checkout branch_tags/dustemisdev.n08_ctsm5.2.018
./bin/git-fleximod update cam
```

I'm getting a slightly different traceback, but it looks like it's fundamentally the same error:

```
$ ./bin/git-fleximod update cam
Recursively checking out submodules of cam

e            chem_proc not checked out, aligned at tag chem_proc5_0_06
e                carma not checked out, aligned at tag carma4_01
e                pumas not checked out, aligned at tag pumas_cam-release_v1.36
e         pumas-frozen not checked out, aligned at tag pumas_cam-release_v1.17_rename
e             ali_arms not checked out, aligned at tag ALI_ARMS_v1.0.1
e           atmos_phys not checked out, aligned at tag atmos_phys0_02_006
e                  fv3 not checked out, aligned at tag fv3int_053124
e             geoschem not checked out, aligned at tag 14.1.2
e                hemco not checked out, aligned at tag hemco-cesm1_2_1_hemco3_6_3_cesm_rme
e           rte-rrtmgp not checked out, aligned at tag v1.7
e          rrtmgp-data not checked out, aligned at tag v1.8
e                 mpas not checked out, aligned at hash b8c33daa
e                cosp2 not checked out, aligned at tag v2.1.4cesm
e                clubb not checked out, aligned at tag clubb_4ncar_20231115_5406350
Recursively checking out submodules of fv3

e   atmos_cubed_sphere not checked out, aligned at tag FV3-202204-public
Recursively checking out submodules of hemco

e                HEMCO has no fxtag defined in .gitmodules
Recursively checking out submodules of HEMCO

e docs/source/geos-chem-shared-docs has no fxtag defined in .gitmodules
Traceback (most recent call last):
  File "/Users/sacks/temporary/CTSM3/./bin/git-fleximod", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/sacks/temporary/CTSM3/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 607, in main
    submodules_update(gitmodules, root_dir, fxrequired, force)
  File "/Users/sacks/temporary/CTSM3/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 421, in submodules_update
    single_submodule_checkout(
  File "/Users/sacks/temporary/CTSM3/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 255, in single_submodule_checkout
    submodules_checkout(gitmodules, repodir, requiredlist, force=force)
  File "/Users/sacks/temporary/CTSM3/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 512, in submodules_checkout
    submodule_sparse_checkout(root_dir, name, url, path, fxsparse, tag=fxtag)
  File "/Users/sacks/temporary/CTSM3/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 106, in submodule_sparse_checkout
    assert os.path.isdir(os.path.join(gitroot, ".git"))
AssertionError
```

**Comment by jedwards4b** [comment]
@billsacks thank you for the clear, complete instructions to reproduce the issue - that was very helpful.  

v0.8.5 solves the problem.

**Comment by billsacks** [comment]
> v0.8.5 solves the problem.

Thank you very much @jedwards4b !

**Comment by ekluzek** [comment]
Yes, this is great. Thanks @jedwards4b and also @billsacks!
